[package]
name = "spacebar-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.5.1"
bitflags = "2.2.1"
chrono = "0.4.24"
futures = "0.3.28"
lazy_static = "1.4.0"
log4rs = "1.2.0"
mysql_async = "0.32.2"
mysql_common = { version = "0.30.3", features = ["chrono"] }
num-bigint = "0.4.3"
poem = "1.3.55"
regex = "1.8.1"
reqwest = "0.11.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
