[package]
name = "symfonia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.5.1"
base64 = "0.21.0"
bcrypt = "0.14.0"
bigdecimal = "0.3.0"
bitflags = { version = "2.2.1", features = ["serde"] }
chrono = { version = "0.4.24", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.28"
hostname = "0.3.1"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = { version = "1.2.0", features=["rolling_file_appender", "compound_policy", "size_trigger", "gzip"] }
num-bigint = "0.4.3"
num-traits = "0.2.15"
openssl = "0.10.52"
poem = "1.3.55"
rand = "0.8.5"
regex = "1.8.1"
reqwest = "0.11.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["raw_value"] }
sqlx = { git = "https://github.com/zert3x/sqlx", branch="feature/skip", features = ["mysql", "sqlite", "json", "chrono", "ipnetwork", "runtime-tokio-native-tls", "any"] }
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
polyphony-types = { git="https://github.com/polyphony-chat/types", features = ["backend"] }#{ git = "https://github.com/polyphony-chat/types" }
sentry = "0.31.2"
