[package]
name = "symfonia"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "symfonia"

[dependencies]
atomic = "0.6.0"
base64 = "0.22.1"
bcrypt = "0.15.1"
bigdecimal = "0.4.3"
bitflags = { version = "2.5.0", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.30"
hostname = "0.4.0"
jsonwebtoken = "9.3.0"
lazy_static = "1.4.0"
log = "0.4.21"
log4rs = { version = "1.3.0", features = [
    "rolling_file_appender",
    "compound_policy",
    "size_trigger",
    "gzip",
] }
num-bigint = "0.4.5"
num-traits = "0.2.19"
openssl = "0.10.64"
poem = "3.0.1"
utoipa = { version = "5.0.0-alpha.0", features = [] }
rand = "0.8.5"
regex = "1.10.4"
reqwest = { version = "0.12.5", default-features = false, features = [
    "http2",
    "macos-system-configuration",
    "charset",
    "rustls-tls-webpki-roots",
] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["raw_value"] }
sqlx = { version = "0.8.2", features = [
    "json",
    "chrono",
    "ipnetwork",
    "runtime-tokio-rustls",
    "any",
] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
sentry = { version = "0.34.0", default-features = false, features = [
    "backtrace",
    "contexts",
    "debug-images",
    "panic",
    "reqwest",
    "rustls",
] }
clap = { version = "4.5.4", features = ["derive"] }
chorus = { features = [
    "backend",
], default-features = false, git = "https://github.com/polyphony-chat/chorus", branch = "dev" }
serde_path_to_error = "0.1.16"
percent-encoding = "2.3.1"
hex = "0.4.3"
itertools = "0.13.0"
tokio-tungstenite = { version = "0.23.1", features = [
    "rustls-tls-webpki-roots",
    "tokio-rustls",
] }
pubserve = { version = "1.1.0", features = ["async", "send"] }
parking_lot = { version = "0.12.3", features = ["deadlock_detection"] }
sqlx-pg-uint = { version = "0.7.2", features = ["serde"] }

[dev-dependencies]
rusty-hook = "0.11.2"
